name: Run Python Unit Tests with Coverage

on:
  workflow_call:

jobs:
  unit-test-python:
    if: |
      startsWith(github.ref, 'refs/heads/feature/') ||
      github.ref == 'refs/heads/dev' ||
      github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f pyproject.toml ]; then
            echo "🔧 Installing via pyproject.toml..."
            pip install .
          elif [ -f requirements.txt ]; then
            echo "📦 Installing via requirements.txt..."
            pip install -r requirements.txt
          else
            echo "⚠️ No requirements.txt or pyproject.toml found."
            exit 1
          fi

          pip install pytest pytest-cov

      - name: Run pytest with coverage
        run: |
          echo "✅ Running tests with coverage..."
          PYTHONPATH=. pytest \
            --cov=. \
            --cov-report=xml \
            --cov-report=html \
            --junitxml=test-results.xml

          echo "📊 Coverage Summary:"
          coverage report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-test-results
          path: test-results.xml

      - name: Upload coverage report (xml)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload coverage report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/
      
      - name: Publish Test Report (visual UI)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Pytest Report
          path: test-results.xml
          reporter: java-junit
