name: CodeQL Analysis

on:
  workflow_call:
    inputs:
      languages:
        description: "List of languages to analyze (JSON array)"
        required: true
        type: string

jobs:
  analyze:
    name: Analyze Code with CodeQL
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' &&
       (github.base_ref == 'main' || github.base_ref == 'dev')) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')

    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(inputs.languages) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild the project
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
